"""add settings table

Revision ID: 73d96938a405
Revises: cd3938cadbc9
Create Date: 2026-08-11 17:21:37.888691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d96938a405'
down_revision = 'cd3938cadbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('business_email', sa.String(length=120), nullable=True),
    sa.Column('business_phone', sa.String(length=50), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('business_website', sa.String(length=200), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('vat', sa.Float(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('date_format', sa.String(length=50), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('primary_color', sa.String(length=30), nullable=True),
    sa.Column('sidebar_style', sa.String(length=20), nullable=True),
    sa.Column('layout_density', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
